DOMAIN_KEYWORDS = {
    "AI": [
        "ai",
        "artificial intelligence",
        "model",
        "llm",
        "foundation model",
        "machine learning",
        "deep learning",
        "neural network",
        "generative ai",
        "multimodal",
        "agent",
        "reasoning",
    ],
    "Aviation": [
        "drone",
        "uav",
        "uas",
        "counter-uas",
        "swarm",
        "airship",
        "blimp",
        "evtol",
        "vtol",
        "aerial",
        "low altitude",
        "low-altitude",
        "utm",
        "bvlos",
        "unmanned aerial",
        "stratospheric",
        "high-altitude platform",
        "haps",
        "aerostat",
    ],
    "Communications": [
        "satellite",
        "5g",
        "6g",
        "network",
        "communications",
        "spectrum",
        "mesh",
        "leo",
        "geo",
        "non-terrestrial",
        "ntn",
        "starlink",
        "broadband",
        "mcptt",
        "mission-critical",
        "private network",
        "tetra",
        "p25",
        "firstnet",
        "lte",
        "telecom",
        "bandwidth",
        "latency",
        "fiber",
        "wireless",
    ],
    "DisasterTech": [
        "disaster communication",
        "network recovery",
        "communication recovery",
        "post-disaster",
        "disaster response",
        "emergency communication",
        "deployable network",
        "resilient network",
        "network resilience",
        "disaster relief",
        "search and rescue",
        "first responder",
        "public safety",
        "incident command",
        "emergency management",
        "fema",
        "wildfire",
        "flood response",
        "earthquake",
        "crisis response",
        "critical infrastructure protection",
        "preparedness",
        "continuity of operations",
        "interoperable communications",
        "tactical network",
    ],
}

REGION_KEYWORDS = {
    "US": ["u.s.", "united states", "fema", "fcc", "nasa", "nist", "firstnet"],
    "Europe": ["eu", "europe", "european", "etsi"],
    "China": ["china", "beijing", "shenzhen", "huawei"],
    "Indo-Pacific": ["indo-pacific", "japan", "australia", "india"],
    "Global": ["itu", "un ", "united nations", "global", "international"],
}
